version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "npm"

  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
      day: "tuesday"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "frontend"
      - "npm"
    groups:
      vitest-dependencies:
        patterns:
          - "vitest"
          - "@vitest/*"

  - package-ecosystem: "npm"
    directory: "/backend"
    schedule:
      interval: "weekly"
      day: "tuesday"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "backend"
      - "npm"
