import Card from '../Card/Card.component'

const toneClasses = {
  default: {
    pill: 'border-neutral-300 bg-surface-input text-foreground',
    card: 'border-neutral-300 bg-surface-raised',
    icon: 'border-neutral-300 bg-surface-app text-heading',
  },
  success: {
    pill: 'border-success bg-success text-on-primary',
    card: 'border-success bg-surface-raised',
    icon: 'border-success bg-success text-on-primary',
  },
  warning: {
    pill: 'border-warning bg-warning text-heading',
    card: 'border-warning bg-surface-raised',
    icon: 'border-warning bg-warning text-heading',
  },
}

function DefaultBadgeIcon() {
  // Default trophy icon for the badge generated by ChatGPT and modified for this project
  return (
    <svg viewBox="0 0 48 48" aria-hidden="true" className="h-12 w-12" fill="none">
      <path d="M16 8h16v5c0 5.7-3.4 10.6-8 12.8-4.6-2.2-8-7.1-8-12.8V8Z" fill="currentColor" />

      <path
        d="M16 10h-4c0 5.2 2.4 8.7 7 10M32 10h4c0 5.2-2.4 8.7-7 10"
        stroke="currentColor"
        strokeWidth="2.5"
        strokeLinecap="round"
      />

      <path d="M24 26v6" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" />

      <rect x="18" y="32" width="12" height="4" rx="1.5" fill="currentColor" />
      <rect x="15" y="37" width="18" height="4" rx="1.5" fill="currentColor" />
    </svg>
  )
}

export default function Badge({
  variant = 'default',
  mode = 'pill',
  label,
  title,
  course = 'Course completion',
  icon,
  earned = true,
  earnedDate,
  className = '',
  children,
  ...props
}) {
  const selectedTone = toneClasses[variant] || toneClasses.default
  const badgeTitle = title || label || children

  if (mode === 'pill') {
    return (
      <span
        className={`inline-flex items-center rounded-pill border px-3 py-1 text-sm font-semibold ${selectedTone.pill} ${className}`.trim()}
        {...props}
      >
        {badgeTitle}
      </span>
    )
  }

  const isEarned = earned

  return (
    <Card
      {...props}
      aria-label={`${typeof badgeTitle === 'string' ? badgeTitle : 'Course'} badge, ${
        isEarned ? 'earned' : 'locked'
      }`}
      className={`flex w-full max-w-md items-center gap-4 ${selectedTone.card} ${!isEarned ? 'opacity-70' : ''} ${className}`}
    >
      <div
        className={`flex h-14 w-14 shrink-0 items-center justify-center rounded-pill border-2 ${selectedTone.icon}`}
      >
        <span aria-hidden="true">{icon || <DefaultBadgeIcon />}</span>
      </div>

      <div className="min-w-0">
        <p className="text-caption font-semibold uppercase tracking-wide text-primary">
          {isEarned ? 'Badge earned' : 'Locked badge'}
        </p>
        <h3 className="mt-1 font-heading text-h4 font-bold text-heading">{badgeTitle}</h3>
        <p className="mt-1 text-small text-neutral-600">{course}</p>
        {isEarned && earnedDate ? (
          <p className="mt-2 text-caption font-medium text-neutral-500">Earned {earnedDate}</p>
        ) : null}
      </div>
    </Card>
  )
}
