export const ROUTES = {
  HOME: '/',
  DEV_COMPONENTS: '/dev/components',
  LOGIN: '/login',
  REGISTER: '/register',
  VERIFY_EMAIL: '/verify',
  PASSWORD_RESET: '/reset-password',
  DASHBOARD: '/dashboard',
  LESSONS: '/lessons',
  LEARN: '/learn',
  LESSON: '/lesson/:moduleId/:lessonId/:microLessonId',
  PROFILE: '/profile',
  PRIVACY: '/privacy',
  TERMS: '/terms',
}
