function DefaultBadgeIcon() {
  // Default trophy icon for the badge generated by ChatGPT and modified for this project
  return (
    <svg viewBox="0 0 48 48" aria-hidden="true" className="h-12 w-12" fill="none">
      <path d="M16 8h16v5c0 5.7-3.4 10.6-8 12.8-4.6-2.2-8-7.1-8-12.8V8Z" fill="currentColor" />

      <path
        d="M16 10h-4c0 5.2 2.4 8.7 7 10M32 10h4c0 5.2-2.4 8.7-7 10"
        stroke="currentColor"
        strokeWidth="2.5"
        strokeLinecap="round"
      />

      <path d="M24 26v6" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" />

      <rect x="18" y="32" width="12" height="4" rx="1.5" fill="currentColor" />
      <rect x="15" y="37" width="18" height="4" rx="1.5" fill="currentColor" />
    </svg>
  )
}

export default function Badge({
  title,
  children,
  course = 'Course completion',
  icon,
  earned = true,
  earnedDate,
  className = '',
  ...props
}) {
  const badgeTitle = title || children

  const badgeStyles = earned
    ? 'border-primary-alt bg-surface-raised'
    : 'border-neutral-300 bg-neutral-100 text-neutral-500'

  const iconStyles = earned
    ? 'border-primary bg-primary-alt text-heading'
    : 'border-neutral-400 bg-neutral-200 text-neutral-500'

  return (
    // Native HTML <article> element used for the badge
    // Accepts all standard HTML <article> attributes via props
    <article
      {...props}
      aria-label={`${typeof badgeTitle === 'string' ? badgeTitle : 'Course'} badge, ${
        earned ? 'earned' : 'locked'
      }`}
      className={`flex w-full max-w-md items-center gap-4 rounded-lg border p-4 shadow-sm ${badgeStyles} ${className}`}
    >
      {/* Badge icon */}
      <div
        className={`flex h-20 w-20 shrink-0 items-center justify-center rounded-pill border-4 ${iconStyles}`}
      >
        <span aria-hidden="true">{icon || <DefaultBadgeIcon />}</span>
      </div>

      {/* Badge details */}
      <div className="min-w-0">
        <p className="text-caption font-semibold uppercase tracking-wide text-primary">
          {earned ? 'Badge earned' : 'Locked badge'}
        </p>

        <h3 className="mt-1 font-heading text-h4 font-bold text-heading">{badgeTitle}</h3>

        <p className="mt-1 text-small text-neutral-600">{course}</p>

        {earned && earnedDate && (
          <p className="mt-2 text-caption font-medium text-neutral-500">Earned {earnedDate}</p>
        )}
      </div>
    </article>
  )
}
